package skoczny.jedynak.poradnik.service;

/**
 * Created by Damian on 2016-01-16.
 */
public class ChorobyOpisy {
    final static public String zapalenieUcha = "czesta choroba wieku dzieciecego. W pierwszym okresie zazwyczaj jest infekcja wirusowa. Jezeli sie przedluza, najczesciej wywolywane jest przez bakterie nalezace do gatunkow Streptococcus pneumoniae, Haemophilus influenzae i Moraxella catarrhalis.";
    final static public String zawal = "ogolne pojecie patomorfologiczne oznaczajace rodzaj martwicy spowodowanej skrajnym ograniczeniem perfuzji (przeplywu) krwi przez obszar tkankowy danego narzadu. Obszar martwicy powstalej w wyniku zawalu moze miec charakter martwicy skrzepowej (necrosis coagulativa, necrosis denaturativa) lub rozplywnej (necrosis colliquativa).";
    final static public String wzdecia = "objaw chorobowy zwiazany z obecnoscia nadmiernej ilosci gazow w jelitach.";
    final static public String marskosc = "postepujace wloknienie miazszu watroby, niszczace jej strukture.";
    final static public String kaszel = "reakcja odruchowa na podraznienie zakonczen nerwowych w blonie sluzowej gornych drog oddechowych.";
    final static public String alergie = "patologiczna, jakosciowo zmieniona odpowiedz tkanek na oddzialywanie roznych obcych substancji zwanych alergenami, polegajaca na reakcji immunologicznej zwiazanej z powstaniem swoistych przeciwcial, ktore po zwiazaniu z antygenem doprowadzaja do uwolnienia roznych substancji mediatorow stanu zapalnego. ";
    final static public String problemyZoladkowe = "objaw chorobowy zwiazany z obecnoscia nadmiernej ilosci gazow w jelitach.";
    final static public String niedoTarczycy = "choroba ludzi i zwierzat spowodowana niedoborem hormonow tarczycy, prowadzacym do spowolnienia procesow metabolicznych.";
    final static public String bolOka = "Bol oczu moze sygnalizowac niegrozna dolegliwosc wywolana na przyklad przeciazeniem wzroku czy podraznieniem spojowek, ale takze moze oznaczac powazna chorobe oczu, taka jak jaskra lub zapalenie nerwu wzrokowego. Dlatego bolu oczu nigdy nie nalezy lekcewazyc.";
    final static public String zapalenieZatok = "stan zapalny zatok przynosowych.";
    final static public String szkorbut = " choroba wielonarzadowa, wywolana niedoborem kwasu askorbinowego w pozywieniu.";
    final static public String hiv = " wirus z rodzaju lentiwirusow, z rodziny retrowirusow. Atakuje glownie limfocyty T-pomocnicze (limfocyty Th). Wiriony maja budowe kulista i otoczone sa otoczka lipidowa, zawierajaca liczne bialka (glikoproteiny: gp120 u HIV-1 i HIV-2 oraz gp41 u HIV-1 i gp36 u HIV-2). Pod oslonka znajduje sie plaszcz bialkowy, czyli kapsyd, kryjacy material genetyczny wirusa (RNA) i enzymy: odwrotna transkryptaze, integraze. Wywoluje AIDS";
    final static public String parkinson = "samoistna, powoli postepujaca, zwyrodnieniowa choroba osrodkowego ukladu nerwowego, nalezaca do chorob ukladu pozapiramidowego.";
    final static public String nerwica = " grupa zaburzen psychicznych o bardzo rozmaitej symptomatyce, definiowana jako zespoly dysfunkcji narzadow, psychogennych zaburzen emocjonalnych, zaklocen procesow psychicznych i patologicznych form zachowania wystepujacych w tym samym czasie i powiazanych ze soba wzajemnie. W obecnie obowiazujacej klasyfikacji ICD-10 termin zaburzen nerwicowych zostal zastapiony terminem zaburzen lekowych. Wiazalo sie to z reorganizacja kategorii zaburzen afektywnych";
    final static public String chorobaSrca = " schorzenia dotyczace narzadow i tkanek wchodzacych w sklad ukladu krazenia, a w szczegolnosci serca, tetnic i zyl, dlatego czesto sa tez nazywane chorobami ukladu sercowo-naczyniowego. ";
    final static public String sucheOko = " schorzenie oczu wywolane niedostatecznym wydzielaniem lez lub nadmiernym parowaniem filmu lzowego. Do jego typowych objawow nalezy: drapanie, uczucie piasku pod powiekami, uczucie obcego ciala, swedzenie, pieczenie, zaczerwienie, bol, obrzekniete powieki, zjawisko podwojnego widzenia, gromadzenie sie wydzieliny w kacikach oka, swiatlowstret.";
    final static public String zakazenieBakteryjne = "Choroby bakteryjne obejmuja dowolny rodzaj choroby powodowane przez bakterie. Bakterie sa rodzaj drobnoustroju, ktore sa male formy zycia, ktore mozna zobaczyc tylko pod mikroskopem. Inne rodzaje mikroorganizmow m.in. wirusy, niektore grzyby i jakies pasozyty.";
    final static public String maizdzyca = "przewlekla choroba, polegajaca na zmianach zwyrodnieniowo-wytworczych w blonie wewnetrznej i srodkowej tetnic, glownie w aorcie, tetnicach wiencowych i mozgowych, rzadziej w tetnicach konczyn. Miazdzyca jest najczestsza przyczyna stwardnienia tetnic (lac. arteriosclerosis).";
    final static public String cukrzyca = "grupa chorob metabolicznych charakteryzujaca sie hiperglikemia (podwyzszonym poziomem cukru we krwi) wynikajaca z defektu produkcji lub dzialania insuliny wydzielanej przez komorki beta trzustki[2]";
    final static public String schizofrenia = " zaburzenie psychiczne zaliczane do grupy psychoz endogennych, czyli stanow charakteryzujacych sie zmienionym chorobowo, nieadekwatnym postrzeganiem, przezywaniem, odbiorem i ocena rzeczywistosci. ";
    final static public String stwardnienieBoczne = "nieuleczalna, postepujaca choroba neurodegeneracyjna, ktora prowadzi do niszczenia komorek rogow przednich rdzenia kregowego, jader nerwow czaszkowych rdzenia przedluzonego oraz neuronow drogi piramidowej, czyli wybiorczego uszkodzenia obwodowego (dolnego) i osrodkowego (gornego) neuronu ruchowego.";
    final static public String luszczyca = "przewlekla, nawracajaca choroba ukladowa mediowana immunologicznie (nalezy do chorob autoimmunizacyjnych), w ktorej procesy zapalne charakteryzujaca sie obecnoscia objawow skornych - luszczacych sie wykwitow - i stawowo-sciegnistych";
    final static public String tradzi = " choroba skory, ktorej poczatek wystepuje w wieku pokwitania, kiedy pod wplywem zmian hormonalnych (nadmiernej stymulacji androgenowej) dochodzi do nadmiernego pobudzenia czynnosci gruczolow lojowych (lojotoku).";
    final static public String suchaSkora = "to termin medyczny na okreslenie przesuszonej skory. Pochodzi z jezyka greckiego; xero znaczy suchy, a osis oznacza chorobe lub zaburzenie zdrowotne. Spowodowana jest ona odwodnieniem skory, ktore moze byc skutkiem starzenia (starcza suchosc skory) lub chorobami, jak cukrzyca.";
    final static public String bole = " wedlug definicji Miedzynarodowego Towarzystwa Badania Bolu subiektywnie przykre i negatywne wrazenie zmyslowe i emocjonalne, powstajace pod wplywem bodzcow uszkadzajacych tkanke (tzw. nocyceptywnych) lub zagrazajacych ich uszkodzeniem. Bol jest odczuciem subiektywnym, dlatego jest nim wszystko to, co chory w ten sposob nazywa, bez wzgledu na obiektywne objawy z nim zwiazane. ";
    final static public String grzybica = "grupa wysoce zarazliwych chorob zakaznych zwierzat, w tym rowniez czlowieka wywolywana przez mikroskopijne grzyby (okolo 200 gat. z 250 000 opisanych).";
    final static public String rakMocz = "choroba nowotworowa pecherza moczowego, najczesciej wywodzaca sie z komorek nablonka przejsciowego (urothelium) blon sluzowych wyscielajacych swiatlo narzadu. Rak (carcinoma) stanowi zdecydowana wiekszosc zlosliwych nowotworow pecherza moczowego.";
    final static public String przerostGr = "choroba wystepujaca u mezczyzn i zwiazana glownie z rozrostem (rozplemem) komorek gruczolowych i komorek podscieliska gruczolu krokowego, a w mniejszym stopniu przerostem komorek (stad niejednoznaczna nomenklatura), powodujaca zwezenie drogi odplywu moczu. Uwaza sie, ze wystepuje u ponad 50% mezczyzn w wieku powyzej 60. roku zycia i z wiekiem czestosc jej wystepowania wzrasta.";
    final static public String bilaczka = " grupa nowotworow zlosliwych o roznym przebiegu i objawach, ktora jest spowodowana patologicznym klonalnym rozrostem komorek ukladu krwiotworczego o roznym stopniu dojrzalosci w szpiku kostnym, a takze w wezlach chlonnych i narzadach krwiotworczych okresu plodowego (watroba, sledziona), a w pozniejszym etapie rowniez w innych tkankach. W konsekwencji choroby dochodzi do zaburzen ilosciowych i jakosciowych komorek krwi obwodowej";
    final static public String anty = " zbior metod lub srodkow sluzacych zapobieganiu ciazy";
    final static public String biegunka = " objaw kliniczny polegajacy na zwiekszonej czestotliwosci wyproznien (wedlug WHO ?3/24h[1]) lub zwiekszonej ilosci stolca (?200g/24h), wraz ze zmiana konsystencji na plynna badz polplynna.";
    final static public String zakazenie = "Wiele roznych wirusow i bakterii wywoluje pierwotne choroby obejmujace drogi oddechowe. Dochodzi do nich w wyniku zaburzen mechanizmow obronnych organizmu, np. w wyniku przemeczenia, przegrzania lub tez przeziebienia. Czesto rowniez mamy do czynienia z wtornymi zakazeniami bakteryjnymi w przebiegu infekcji poczatkowo wirusowej. Szczegolnie narazone na nadkazenia sa niemowleta i male dzieci, u ktorych zakazenia wirusowe prowadza do rozleglego uszkodzenia blony sluzowej, uposledzaja odpornosc miejscowa w obrebie ukladu oddechowego, stwarzajac dogodne warunki do wtornego namnazania sie bakterii.";
    final static public String alzheimer = "najczestsza postac otepienia, nieuleczalna i postepujaca choroba neurodegeneracyjna, prowadzaca do smierci pacjenta.";
    final static public String przeziebienie = " wirusowa choroba zakazna gornych drog oddechowych ze szczegolnie nasilonymi objawami w obrebie nosa. ";
    final static public String niedoborWapnia = "Hipokalcemia objawia sie miedzy innymi pobudliwoscia nerwowo–miesniowa, uczuciem dretwienia konczyn i okolicy ust, zaburzeniem odruchow nerwowych, skurczami miesni, tezyczka lub drgawkami. Moze byc takze przyczyna zaburzen rytmu serca.";
    final static public String grzybicaSkory = grzybica;
    final static public String grypa = " ostra choroba zakazna ukladu oddechowego wywolana zakazeniem wirusem grypy.";
    final static public String refluks = "chorzenie, polegajace na nieprawidlowym cofaniu sie kwasnej tresci zoladkowej do przelyku, z powodu niesprawnosci zwieracza dolnego przelyku";
    final static public String bialaczka = " grupa nowotworow zlosliwych o roznym przebiegu i objawach, ktora jest spowodowana patologicznym klonalnym rozrostem komorek ukladu krwiotworczego o roznym stopniu dojrzalosci w szpiku kostnym, a takze w wezlach chlonnych i narzadach krwiotworczych okresu plodowego (watroba, sledziona), a w pozniejszym etapie rowniez w innych tkankach. W konsekwencji choroby dochodzi do zaburzen ilosciowych i jakosciowych komorek krwi obwodowej";
    final static public String ukaszenie = "W miejscu ukaszenia przez owady pojawia sie czerwona plamka (rumien) i opuchniecie. Czujesz tez bol. Wszystko mija jednak po kilku godzinach. Ale alergia na jad owadow moze byc uogolniona i objawic sie w postaci pokrzywki lub obrzeku, ktory obejmuje twarz, wargi i powieki";
    final static public String nerki = "stan uposledzenia nerek ponad mozliwosci fizjologiczne ich kompensacji. Wyroznia sie stan przewlekly i ostry.";
    final static public String skora = "Choroby skory moga sie ujawniac w postaci plamek, grudek, babli, cyst, guzkow, pecherzy, rumienia czy krost. Objawom tym moga towarzyszyc swiad, pieczenie skory i bolesnosc. Wsrod najczestszych chorob skory wymienia sie reakcje alergiczna, grzybice, tradzik czy AZS";
    final static public String nosAlergia = "Alergiczne zapalenie blony sluzowej nosa (AZBsN) jest choroba, ktorej przyczyna jest mediowana przez IgE reakcja atopowa w obrebie blony sluzowej nosa rozwijajaca sie po ekspozycji alergenowej.";
    final static public String katar = "pojecie dotyczace objawow zapalenia blony sluzowej nosa (niekiedy takze zatok przynosowych). Do objawow naleza: kichanie, drapanie (swiad w nosie i gardle, kaszel, pieczenie spojowek, wyciek plynnej wydzieliny z nosa, lub jej splywanie po tylnej scianie gardla, zatkany nos, ogolne oslabienie, bol glowy, stan podgoraczkowy. Niezyt nosa diagnozuje sie, gdy objawy te trwaja przez dwa lub wiecej kolejnych dni oraz dluzej niz jedna godzine przez wiekszosc tych dni";
    final static public String zaburzeniaFlory = " zespol chorobowy przebiegajacy z nadmiernym rozrostem w jelicie czczym flory bakteryjnej typowej dla jelita grubego, ktory powoduje zaburzenia trawienia oraz wchlaniania pokarmow, a zwlaszcza tluszczow i witaminy B12.";
    final static public String zapalanie = "zwane wypryskiem atopowym, egzema, a niegdys swierzbiaczka (lac. prurigo) Besniera, wypryskiem alergicznym lub alergicznym zapaleniem skory, w dermatologii i alergologii okreslane jako przewlekla dermatoza (zapalna) – przebiegajaca z okresami zaostrzen i remisji choroba skory, ktorej towarzyszy uporczywy i nawrotowy swiad oraz liszajowacenie skory[1].";
    final static public String zapalanieInt = "druga, po bakteryjnym zapaleniu pochwy, najczestsza przyczyna infekcji drog moczowo-plciowych kobiety.";
    final static public String zapWatroby = "grupa chorob watroby o roznej etiologii, ktorych wspolnym mianownikiem jest stan zapalny tego narzadu.";
    final static public String wit = "schorzenie polegajace na calkowitym braku lub znaczacym niedoborze witaminy[1] lub ich zestawu w organizmie. Powoduje roznorodne zaklocenia przemiany materii z objawami charakterystycznymi dla poszczegolnych witamin.";
    final static public String depresja = "pojecie stosowane w terminologii psychiatrycznej, odnoszace sie do zespolow objawow depresyjnych wystepujacych w przebiegu chorob afektywnych (okreslanych takze jako zaburzenia afektywne, zaburzenia nastroju).";

}
